version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel_test_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel-test-network

  webserver:
    image: nginx:alpine
    container_name: laravel_test_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-test-network
    depends_on:
      - app

  db:
    image: mysql:8.4
    container_name: laravel_test_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_test
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: laravel_test_user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-test-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_test_pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123
    ports:
      - "8080:80"
    networks:
      - laravel-test-network
    depends_on:
      - db

networks:
  laravel-test-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
